src/objects/DFDemo_Filter_Criteria__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Used to create filter criteria for queries or evaluations in the code for project.</description>
    <fields>
        <fullName>Current_Band_Max__c</fullName>
        <defaultValue>100</defaultValue>
        <description>The maximum band used for evaluation by the work flow to trigger the on boarding evaluation process.</description>
        <inlineHelpText>The maximum band used for evaluation by the work flow to trigger the on boarding evaluation process.</inlineHelpText>
        <label>Current Band Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Band_Min__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The minimum band used for evaluation by the work flow to trigger the on boarding evaluation process.</description>
        <inlineHelpText>The minimum band used for evaluation by the work flow to trigger the on boarding evaluation process.</inlineHelpText>
        <label>Current Band Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DFDemo Filter Criteria</label>
</CustomObject>

src/classes/DFDemo_FilterCriteriaTest.cls
@isTest
public class DFDemo_FilterCriteriaTest{

   	@isTest
	private static void testDefaultValues() {
        String TEST_NAME = 'MosIsley';
        System.assertEquals(DFDemo_FilterCriteria.CURR_BAND_MAX, DFDemo_FilterCriteria.get().getCurrentBandMax());
        System.assertEquals(DFDemo_FilterCriteria.CURR_BAND_MIN, DFDemo_FilterCriteria.get().getCurrentBandMin());
        
        DFDemo_FilterCriteria.clear();
        
		Test.startTest();
            DFDemo_Filter_Criteria__c filter = new DFDemo_Filter_Criteria__c();
            filter.Name = TEST_NAME;
            filter.SetupOwnerId = UserInfo.getOrganizationId();
            filter.Current_Band_Max__c = DFDemo_FilterCriteria.CURR_BAND_MAX;
            filter.Current_Band_Min__c = DFDemo_FilterCriteria.CURR_BAND_MIN;
            insert filter;
        Test.stopTest();
        
        System.assertEquals(DFDemo_FilterCriteria.CURR_BAND_MAX, DFDemo_FilterCriteria.get(TEST_NAME).getCurrentBandMax());
        System.assertEquals(DFDemo_FilterCriteria.CURR_BAND_MIN, DFDemo_FilterCriteria.get(TEST_NAME).getCurrentBandMin());
    }
}